//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/InputSystem/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""34322ca9-a85b-471f-9c5a-b72f9d784125"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ba0b75ed-df6e-476b-bc76-8f0e1276d114"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XMove"",
                    ""type"": ""Value"",
                    ""id"": ""b44968cf-90ce-4908-9c85-18fa502db90f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rush"",
                    ""type"": ""Button"",
                    ""id"": ""32b189ab-7bdd-49bb-99e8-e2a1635fb9e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""bc6b1144-42ad-4a21-86b7-b93d17782053"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""cfe6566f-0528-41ed-b8b4-abd596eb50fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Giveup"",
                    ""type"": ""Button"",
                    ""id"": ""7917b794-7dfc-41e2-b5bf-90f2cc57d310"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EndEditing"",
                    ""type"": ""Button"",
                    ""id"": ""8e8600bd-2a84-4df7-9e2d-6157ce2a3f14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""6088b49c-684c-4424-adf9-2b63bfcc20f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""66a05f93-9957-41c4-b734-9eeb3fa7ccca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""A/D"",
                    ""id"": ""12bdf976-e2df-4ced-bdc0-8809021b1d60"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e199fbe2-e559-4ccc-91fb-0b9f63865aa2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dc4dc768-f263-4e61-9dea-9cc265e2a838"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7d2de6b7-f49b-497e-8166-839cbd0f4613"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cc860e7-7919-4379-beb1-b8f4f65bb623"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""477862dd-aa0a-4c91-8ba0-8d254824d271"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f977f241-3566-4130-b1d3-077a1a880e76"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Giveup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbb8fc57-c041-4178-bff5-377f72f9f056"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EndEditing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a351a83c-3fba-4a0f-9d3b-4e955298c3d9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InEdit"",
            ""id"": ""31731fa2-2d31-4a3d-9445-e9fe7781ef79"",
            ""actions"": [
                {
                    ""name"": ""PointerPos"",
                    ""type"": ""Value"",
                    ""id"": ""cd3cfa05-f60a-4707-86a4-9191140bfc64"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Giveup"",
                    ""type"": ""Button"",
                    ""id"": ""ddc84ba5-1b3e-4cef-b9b7-f1eaa6da122c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""fc737efb-4bc4-40a1-9b8d-a91844003679"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""707b28e1-79ac-486e-8abe-5c389c320dc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnLeft"",
                    ""type"": ""Button"",
                    ""id"": ""aebf9511-6696-4d10-9d2e-78c7bf207c0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnRight"",
                    ""type"": ""Button"",
                    ""id"": ""b85a0258-1a78-4e7f-b7bc-033ce2b79516"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""64c21702-55b2-48b9-9165-e4b437ec7f71"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ea34bb7-152e-4f4e-bdc3-af26c6d9e24e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9892e51d-d414-49b4-a786-b3bc822635ba"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2585f6a4-19a8-4b03-a69c-4b4747db08dc"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13030fca-9f91-4cc1-9d05-353a96e676b0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48da4fbd-ca57-45c7-b531-1c84d24c9da1"",
                    ""path"": ""<Mouse>/{Back}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eda53a8e-5988-4c2d-8a7b-1dbac6d831aa"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5145af45-1909-4c07-a5a4-eed8841d3e8a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Giveup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InEureka"",
            ""id"": ""d8aabc33-1ff7-40d2-954f-3975ad3f1c07"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""62ed221e-cb0f-4c3a-8786-afe83d74f2e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ffdd547d-f533-4071-ade7-7a5febbffcaa"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Jump = m_InGame.FindAction("Jump", throwIfNotFound: true);
        m_InGame_XMove = m_InGame.FindAction("XMove", throwIfNotFound: true);
        m_InGame_Rush = m_InGame.FindAction("Rush", throwIfNotFound: true);
        m_InGame_Crouch = m_InGame.FindAction("Crouch", throwIfNotFound: true);
        m_InGame_Restart = m_InGame.FindAction("Restart", throwIfNotFound: true);
        m_InGame_Giveup = m_InGame.FindAction("Giveup", throwIfNotFound: true);
        m_InGame_EndEditing = m_InGame.FindAction("EndEditing", throwIfNotFound: true);
        m_InGame_Dash = m_InGame.FindAction("Dash", throwIfNotFound: true);
        // InEdit
        m_InEdit = asset.FindActionMap("InEdit", throwIfNotFound: true);
        m_InEdit_PointerPos = m_InEdit.FindAction("PointerPos", throwIfNotFound: true);
        m_InEdit_Giveup = m_InEdit.FindAction("Giveup", throwIfNotFound: true);
        m_InEdit_Cancel = m_InEdit.FindAction("Cancel", throwIfNotFound: true);
        m_InEdit_Confirm = m_InEdit.FindAction("Confirm", throwIfNotFound: true);
        m_InEdit_TurnLeft = m_InEdit.FindAction("TurnLeft", throwIfNotFound: true);
        m_InEdit_TurnRight = m_InEdit.FindAction("TurnRight", throwIfNotFound: true);
        // InEureka
        m_InEureka = asset.FindActionMap("InEureka", throwIfNotFound: true);
        m_InEureka_Confirm = m_InEureka.FindAction("Confirm", throwIfNotFound: true);
    }

    ~@Player()
    {
        UnityEngine.Debug.Assert(!m_InGame.enabled, "This will cause a leak and performance issues, Player.InGame.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_InEdit.enabled, "This will cause a leak and performance issues, Player.InEdit.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_InEureka.enabled, "This will cause a leak and performance issues, Player.InEureka.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Jump;
    private readonly InputAction m_InGame_XMove;
    private readonly InputAction m_InGame_Rush;
    private readonly InputAction m_InGame_Crouch;
    private readonly InputAction m_InGame_Restart;
    private readonly InputAction m_InGame_Giveup;
    private readonly InputAction m_InGame_EndEditing;
    private readonly InputAction m_InGame_Dash;
    public struct InGameActions
    {
        private @Player m_Wrapper;
        public InGameActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_InGame_Jump;
        public InputAction @XMove => m_Wrapper.m_InGame_XMove;
        public InputAction @Rush => m_Wrapper.m_InGame_Rush;
        public InputAction @Crouch => m_Wrapper.m_InGame_Crouch;
        public InputAction @Restart => m_Wrapper.m_InGame_Restart;
        public InputAction @Giveup => m_Wrapper.m_InGame_Giveup;
        public InputAction @EndEditing => m_Wrapper.m_InGame_EndEditing;
        public InputAction @Dash => m_Wrapper.m_InGame_Dash;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @XMove.started += instance.OnXMove;
            @XMove.performed += instance.OnXMove;
            @XMove.canceled += instance.OnXMove;
            @Rush.started += instance.OnRush;
            @Rush.performed += instance.OnRush;
            @Rush.canceled += instance.OnRush;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
            @Giveup.started += instance.OnGiveup;
            @Giveup.performed += instance.OnGiveup;
            @Giveup.canceled += instance.OnGiveup;
            @EndEditing.started += instance.OnEndEditing;
            @EndEditing.performed += instance.OnEndEditing;
            @EndEditing.canceled += instance.OnEndEditing;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @XMove.started -= instance.OnXMove;
            @XMove.performed -= instance.OnXMove;
            @XMove.canceled -= instance.OnXMove;
            @Rush.started -= instance.OnRush;
            @Rush.performed -= instance.OnRush;
            @Rush.canceled -= instance.OnRush;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
            @Giveup.started -= instance.OnGiveup;
            @Giveup.performed -= instance.OnGiveup;
            @Giveup.canceled -= instance.OnGiveup;
            @EndEditing.started -= instance.OnEndEditing;
            @EndEditing.performed -= instance.OnEndEditing;
            @EndEditing.canceled -= instance.OnEndEditing;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);

    // InEdit
    private readonly InputActionMap m_InEdit;
    private List<IInEditActions> m_InEditActionsCallbackInterfaces = new List<IInEditActions>();
    private readonly InputAction m_InEdit_PointerPos;
    private readonly InputAction m_InEdit_Giveup;
    private readonly InputAction m_InEdit_Cancel;
    private readonly InputAction m_InEdit_Confirm;
    private readonly InputAction m_InEdit_TurnLeft;
    private readonly InputAction m_InEdit_TurnRight;
    public struct InEditActions
    {
        private @Player m_Wrapper;
        public InEditActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointerPos => m_Wrapper.m_InEdit_PointerPos;
        public InputAction @Giveup => m_Wrapper.m_InEdit_Giveup;
        public InputAction @Cancel => m_Wrapper.m_InEdit_Cancel;
        public InputAction @Confirm => m_Wrapper.m_InEdit_Confirm;
        public InputAction @TurnLeft => m_Wrapper.m_InEdit_TurnLeft;
        public InputAction @TurnRight => m_Wrapper.m_InEdit_TurnRight;
        public InputActionMap Get() { return m_Wrapper.m_InEdit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InEditActions set) { return set.Get(); }
        public void AddCallbacks(IInEditActions instance)
        {
            if (instance == null || m_Wrapper.m_InEditActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InEditActionsCallbackInterfaces.Add(instance);
            @PointerPos.started += instance.OnPointerPos;
            @PointerPos.performed += instance.OnPointerPos;
            @PointerPos.canceled += instance.OnPointerPos;
            @Giveup.started += instance.OnGiveup;
            @Giveup.performed += instance.OnGiveup;
            @Giveup.canceled += instance.OnGiveup;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @TurnLeft.started += instance.OnTurnLeft;
            @TurnLeft.performed += instance.OnTurnLeft;
            @TurnLeft.canceled += instance.OnTurnLeft;
            @TurnRight.started += instance.OnTurnRight;
            @TurnRight.performed += instance.OnTurnRight;
            @TurnRight.canceled += instance.OnTurnRight;
        }

        private void UnregisterCallbacks(IInEditActions instance)
        {
            @PointerPos.started -= instance.OnPointerPos;
            @PointerPos.performed -= instance.OnPointerPos;
            @PointerPos.canceled -= instance.OnPointerPos;
            @Giveup.started -= instance.OnGiveup;
            @Giveup.performed -= instance.OnGiveup;
            @Giveup.canceled -= instance.OnGiveup;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @TurnLeft.started -= instance.OnTurnLeft;
            @TurnLeft.performed -= instance.OnTurnLeft;
            @TurnLeft.canceled -= instance.OnTurnLeft;
            @TurnRight.started -= instance.OnTurnRight;
            @TurnRight.performed -= instance.OnTurnRight;
            @TurnRight.canceled -= instance.OnTurnRight;
        }

        public void RemoveCallbacks(IInEditActions instance)
        {
            if (m_Wrapper.m_InEditActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInEditActions instance)
        {
            foreach (var item in m_Wrapper.m_InEditActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InEditActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InEditActions @InEdit => new InEditActions(this);

    // InEureka
    private readonly InputActionMap m_InEureka;
    private List<IInEurekaActions> m_InEurekaActionsCallbackInterfaces = new List<IInEurekaActions>();
    private readonly InputAction m_InEureka_Confirm;
    public struct InEurekaActions
    {
        private @Player m_Wrapper;
        public InEurekaActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_InEureka_Confirm;
        public InputActionMap Get() { return m_Wrapper.m_InEureka; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InEurekaActions set) { return set.Get(); }
        public void AddCallbacks(IInEurekaActions instance)
        {
            if (instance == null || m_Wrapper.m_InEurekaActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InEurekaActionsCallbackInterfaces.Add(instance);
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
        }

        private void UnregisterCallbacks(IInEurekaActions instance)
        {
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
        }

        public void RemoveCallbacks(IInEurekaActions instance)
        {
            if (m_Wrapper.m_InEurekaActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInEurekaActions instance)
        {
            foreach (var item in m_Wrapper.m_InEurekaActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InEurekaActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InEurekaActions @InEureka => new InEurekaActions(this);
    public interface IInGameActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnXMove(InputAction.CallbackContext context);
        void OnRush(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnRestart(InputAction.CallbackContext context);
        void OnGiveup(InputAction.CallbackContext context);
        void OnEndEditing(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
    public interface IInEditActions
    {
        void OnPointerPos(InputAction.CallbackContext context);
        void OnGiveup(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnTurnLeft(InputAction.CallbackContext context);
        void OnTurnRight(InputAction.CallbackContext context);
    }
    public interface IInEurekaActions
    {
        void OnConfirm(InputAction.CallbackContext context);
    }
}
